### ISSUE TITLE
Graffiti Problem from June 24 to July 1?

### ISSUE THREAD

**Issue by JHGrove3** [gobitfly/eth2-beaconchain-explorer#921]
I was looking at the number of proposals made by different Graffiti tags when I noticed a gap in the data.

When I search Beaconcha.in for a popular graffiti tag (like BitCoinSuisse.com, for example) there is a big gap in the data from June 24 at about 10:34 UTC, and no further tags were recorded (or they are not shown in the report) until July 1 at about 9:01 UTC.

I'm not sure what is causing this problem, but it appears that the data needs to be recompiled for that missing period.

![No Proposal Graffiti Jun 25 - Jul 1](https://user-images.githubusercontent.com/2583972/124697329-33d0df80-deac-11eb-880a-f0dfbf321a3e.png)

**Comment by Buttaa** [comment]
@JHGrove3 The pool may have turned their graffiti off for that period. Have you found a validator which has proposed a block with that graffiti in the given period?

**Comment by guybrush** [comment]
Thank you for letting us know!

This has been fixed now.

**Comment by JHGrove3** [comment]
I am still seeing this bug as of Aug 2, 2021.

![image](https://user-images.githubusercontent.com/2583972/127937104-cf67b6b8-284f-4f6f-a23f-f417f1a4935c.png)
